import { Inter } from "next/font/google";
import CommonLayout from "@/components/Layout/CommonLayout";
// import "bootstrap/dist/css/bootstrap.min.css"
import "../assets/styles/bootstrap.custom.css";
import "../assets/styles/index.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <CommonLayout>{children}</CommonLayout>
            </body>
        </html>
    );
}
